config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses 
  root 'expenses#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
before_action :find_expense, only: [:show, :edit, :update, :destroy]

  def index
    # going to pass through a category hash - if it's blank everything 
    if params[:category].blank?
      @expenses = Expense.all.order("created_at DESC")
    else 
    # if the hash has a specific id, we're going to only show those expenses
      @category_id = Category.find_by(name: params[:category]).id
      @expenses = Expense.where(category_id: @category_id).order("created_at DESC")
    end 
    @spent_money = Expense.where(user_id: current_user)
    @owed_money = Expense.where(user_id: current_user)
  end 

  def show
  end 
  
  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expenses_params)
    @expense.user_id = current_user.id

    if @expense.save 
      redirect_to @expense
    else 
      render "New"
    end 
  end

  def edit
    
  end

  def update
    if @expense.update(expenses_params)
      redirect_to @expense
    else 
      render "Edit"
    end 
    
  end

  def destroy
    @expense.destroy
    redirect_to root_path
  end

  private

  def expenses_params
    params.require(:expense).permit(:title, :amount, :category_id, :user_id)
  end 

  def find_expense
    @expense = Expense.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense, html: { class: 'form-horizontal'}) do |f| %>

  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"} %>
  <br>
  <br>
  <%= f.button :submit %>

<% end %>

app/views/expenses/edit.html.erb
<h1> Edit Job </h1>
<%= render 'form.html.erb' %>
<%= link_to "Back", root_path %>

app/views/expenses/index.html.erb
<% @expenses.each do |ex| %> 

  <h2> <%= link_to ex.title, ex %> </h2>
  <h3> How much did it cost? <%= ex.amount %> </h3>  
  <h3> Who paid for this? <%= ex.user.email %></h3>

<% end %>
<h1>You spent: <%= @spent_money.sum("amount") %> </h1>
<h3>Total This week = <%= @expenses.sum("amount") %></h1>
<h1>You owe: <%= (@expenses.sum("amount"))/2) - ((@spent_money.sum("amount")) %></h1>

<br>
<br>

<!-- How much have you paid for stuff this much? -->


<!-- How much have other users? -->


<!-- How much do you owe? -->

app/views/expenses/new.html.erb
<h1> New Expense </h1>
<%= render 'form.html.erb' %>
<%= link_to "Back", root_path %>

app/views/expenses/show.html.erb
<h1> 
  <%= @expense.title %> 
</h1>

<p> 
  <%= @expense.amount %>
<p>

<p>
  <%= @expense.category_id %>
<p>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_expense_path %>
<%= link_to "Delete", expense_path(@expense), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li><%= link_to "All Expenses", root_path %></li>
         <li><% Category.all.each do |category| %> 
                <button class="btn btn-default">
                  <%= link_to category.name, expenses_path(category: category.name) %>
                </button>
              <% end %>
          </li>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-link">
      <% if user_signed_in? %> 
        <li><%= link_to "Add Expense", new_expense_path %></li>
        <li><%= lik_to 'Edit profile', edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %> 

      <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matt and Stefje's Expenses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
           <li><%= link_to "All Expenses", root_path %></li>
           <li><% Category.all.each do |category| %> 
                  <button class="btn btn-default">
                    <%= link_to category.name, expenses_path(category: category.name) %>
                  </button>
                <% end %>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right navbar-link">
          <%if user_signed_in? %>
            <li><%= link_to "Add Expense", new_expense_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Create Account", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>